./" This is the manpage for _printf
.TH _printf 3 "2016-11-23" "V0.1" "_printf man page"

.SH NAME
_printf

.SH DESCRIPTION
The _printf function accepts and prints various datatypes to standard output. 

.SH OPTIONS

.IP %c
Prints the specified character
.IP %s
Prints the specified string
.IP %%
Prints a single percentage sign
.IP %d
Prints an integer
.IP %i
Prints an integer. There is no difference between %i and %d

.SH AUTHORS
Kina Lee and Danton Rodriguez
